repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run --project ml ruff format
        language: system
        types: [python]
      - id: ruff-check
        name: ruff check
        entry: uv run --project ml ruff check --fix
        language: system
        types: [python]
