/**
 * Contract code generation (spec §6.1): TypeScript types and Ajv standalone validators from the
 * JSON Schemas that `churnvalue contracts` writes to ../contracts/schemas. The outputs are
 * committed; a unit test regenerates them in memory and fails on any difference.
 */
import { readdirSync, readFileSync } from "node:fs";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";

import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { compile, type JSONSchema } from "json-schema-to-typescript";

export const SCHEMAS_DIR = fileURLToPath(new URL("../../contracts/schemas", import.meta.url));
export const OUT_DIR = fileURLToPath(new URL("../src/contract", import.meta.url));
const BANNER = "// Generated by scripts/gen-contract.ts from contracts/schemas. Do not edit.\n";

/** The files the site fetches; golden vectors are read by tests only and need no validator. */
export const ARTIFACT_SCHEMAS = [
  "manifest",
  "customers",
  "timelines",
  "evaluation",
  "experiments",
  "feature_spec",
  "calibrator",
] as const;

type Schema = Record<string, unknown>;

/** Schema names, e.g. "manifest" for manifest.schema.json, sorted. */
export function schemaNames(dir = SCHEMAS_DIR): string[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".schema.json"))
    .map((f) => basename(f, ".schema.json"))
    .sort();
}

function readSchema(name: string, dir: string): Schema {
  return JSON.parse(readFileSync(join(dir, `${name}.schema.json`), "utf8")) as Schema;
}

/** json2ts names the root type after the schema's title (the Pydantic class name). */
function rootTypeName(name: string, dir: string): string {
  const title = readSchema(name, dir).title;
  if (typeof title !== "string") throw new Error(`${name}.schema.json has no title`);
  return title;
}

/** Drop property-level titles: Pydantic adds one per field, which json2ts turns into aliases. */
function withoutPropertyTitles(node: unknown, isRoot = true): unknown {
  if (Array.isArray(node)) return node.map((n: unknown) => withoutPropertyTitles(n, false));
  if (node === null || typeof node !== "object") return node;
  const out: Schema = {};
  for (const [key, value] of Object.entries(node as Schema)) {
    if (key === "properties" && value && typeof value === "object") {
      out[key] = Object.fromEntries(
        Object.entries(value as Schema).map(([prop, sub]) => {
          const rest: Schema = { ...(sub as Schema) };
          delete rest.title;
          return [prop, withoutPropertyTitles(rest, false)];
        }),
      );
    } else if (key === "$defs" && value && typeof value === "object") {
      out[key] = Object.fromEntries(
        Object.entries(value as Schema).map(([def, sub]) => [
          def,
          withoutPropertyTitles(sub, true),
        ]),
      );
    } else {
      out[key] = isRoot || key !== "title" ? withoutPropertyTitles(value, false) : value;
    }
  }
  return out;
}

/**
 * Drop OpenAPI's `discriminator` (Pydantic tags the calibrator union with it). Ajv cannot read its
 * `mapping`, and the `oneOf` already enforces the rule: each variant pins `method` to a constant.
 */
function withoutDiscriminators(node: unknown): unknown {
  if (Array.isArray(node)) return node.map((n: unknown) => withoutDiscriminators(n));
  if (node === null || typeof node !== "object") return node;
  return Object.fromEntries(
    Object.entries(node as Schema)
      .filter(([key]) => key !== "discriminator")
      .map(([key, value]) => [key, withoutDiscriminators(value)]),
  );
}

/** One `types/<name>.gen.ts` of TypeScript types per schema. */
async function typeModules(dir: string): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  for (const name of schemaNames(dir)) {
    const schema = withoutPropertyTitles(readSchema(name, dir)) as JSONSchema;
    const ts = await compile(schema, rootTypeName(name, dir), {
      bannerComment: "",
      additionalProperties: false,
      unreachableDefinitions: true,
      style: { printWidth: 100 },
    });
    out.set(`types/${name}.gen.ts`, BANNER + ts);
  }
  return out;
}

/** A single ESM module exporting one compiled validator per artifact schema. */
function validatorModule(dir: string): string {
  const ajv = new Ajv2020({
    code: { source: true, esm: true, lines: true },
    allErrors: false,
    // Dates stay strings in the app; their shape is checked by Python on write.
    formats: { date: true, "date-time": true },
  });
  const exports: Record<string, string> = {};
  for (const name of ARTIFACT_SCHEMAS) {
    ajv.addSchema(withoutDiscriminators(readSchema(name, dir)) as object, name);
    exports[`validate_${name}`] = name;
  }
  return BANNER + "/* eslint-disable */\n" + standaloneCode(ajv, exports);
}

/** Type declarations for the validators: each one is a type guard for its artifact. */
function validatorDeclarations(dir: string): string {
  const lines = [BANNER.trimEnd(), 'import type { ValidateFunction } from "ajv";', ""];
  for (const name of ARTIFACT_SCHEMAS) {
    lines.push(`import type { ${rootTypeName(name, dir)} } from "./types/${name}.gen.ts";`);
  }
  lines.push("");
  for (const name of ARTIFACT_SCHEMAS) {
    lines.push(
      `export declare const validate_${name}: ValidateFunction<${rootTypeName(name, dir)}>;`,
    );
  }
  return lines.join("\n") + "\n";
}

/** Every generated file, relative to src/contract, with its text. */
export async function generate(dir = SCHEMAS_DIR): Promise<Map<string, string>> {
  const files = await typeModules(dir);
  files.set("validators.gen.js", validatorModule(dir));
  files.set("validators.gen.d.ts", validatorDeclarations(dir));
  return files;
}
