"""Model card (Mitchell et al., 2019) generated from the evaluation outputs, never hand-edited."""

from __future__ import annotations

from typing import Any

import pandas as pd

from churnvalue.contract import Manifest

CALIBRATION_LABELS = {"isotonic": "isotonic", "platt": "Platt"}
METRIC_LABELS = {
    "pr_auc": "PR-AUC",
    "roc_auc": "ROC-AUC",
    "brier": "Brier",
    "lift_at_10": "Lift@10%",
}


def _estimate(e: dict[str, float], digits: int = 3) -> str:
    return f"{e['value']:.{digits}f} [{e['ci_low']:.{digits}f}, {e['ci_high']:.{digits}f}]"


def _gbp(value: float | None) -> str:
    if value is None:
        return "–"
    sign = "−" if value < 0 else ""
    return f"{sign}£{abs(value):,.0f}"


def _share(value: float | None) -> str:
    if value is None:
        return "–"
    return f"{value:.0%}".replace("-", "−")


def render_model_card(
    manifest: Manifest,
    evaluation: dict[str, Any],
    training: dict[str, dict[str, Any]],
    importance: pd.Series,
) -> str:
    name = manifest.deployed_model
    model = evaluation["models"][name]
    trained = training[name]
    split = evaluation["split"]
    test_pop = evaluation["test_population"]
    policies = {row["policy"]: row for row in evaluation["policies"]}
    deployed = policies[name]
    econ = evaluation["economics"]

    lines = [
        "# Model card — churn-value",
        "",
        "> Generated by `churnvalue export` from the evaluation outputs. Do not edit by hand.",
        "",
        "## Model details",
        "",
        f"- **Deployed model:** `{name}` — LightGBM, tuned with Optuna under rolling-origin "
        f"cross-validation (mean validation log loss {trained['cv_log_loss']:.4f}), "
        f"then {CALIBRATION_LABELS[model['calibrator']['method']]} calibration on the "
        f"{split['calibration']} cutoff.",
        f"- **Inputs:** {len(trained['features'])} features computed at the cutoff: base "
        "customer history, arithmetic derived features and the cutoff month (context).",
        "- **Output:** calibrated probability that the customer makes no purchase in the next "
        "90 days, used to rank customers by expected retention profit.",
        f"- **Provenance:** code `{manifest.git_sha}`, data SHA-256 "
        f"`{manifest.data_sha256[:12]}…`, config SHA-256 `{manifest.config_sha256[:12]}…`, "
        f"contract {manifest.contract_version}, created {manifest.created_at:%Y-%m-%d}.",
        "",
        "## Intended use",
        "",
        "- Monthly batch scoring of an online wholesaler's active customers to decide whom to "
        "offer a retention incentive, under explicit economic assumptions.",
        "- Not intended for decisions about individuals beyond marketing contact, for other "
        "businesses without retraining, or as a causal estimate of what an incentive achieves.",
        "",
        "## Data",
        "",
        "- UCI Online Retail II (Chen, 2012), CC BY 4.0: a UK online wholesaler, "
        "Dec 2009 – Dec 2011.",
        f"- Training cutoffs: {split['train'][0]} to {split['train'][-1]} "
        f"({len(split['train'])} monthly snapshots); calibration {split['calibration']}; "
        f"test {split['test']} ({test_pop['n_customers']:,} customers, churn rate "
        f"{test_pop['churn_rate']:.1%}).",
        "",
        "## Evaluation on the test cutoff (95 % customer-clustered bootstrap CIs)",
        "",
        "| Model | " + " | ".join(METRIC_LABELS.values()) + " | Mean p | EMP (£/customer) |",
        "|---|" + "---|" * (len(METRIC_LABELS) + 2),
    ]
    for model_name, body in evaluation["models"].items():
        cells = [_estimate(body["metrics"][key]) for key in METRIC_LABELS]
        lines.append(
            f"| `{model_name}` | "
            + " | ".join(cells)
            + f" | {body['mean_p']:.3f} | {_estimate(body['emp_per_customer'], 2)} |"
        )
    lines += [
        "",
        f"Actual churn rate on the test cutoff: {test_pop['churn_rate']:.3f}.",
        "",
        "## Business result at the default scenario",
        "",
        f"Margin {econ['margin']:.0%}, λc {econ['lambda_c']}, λa {econ['lambda_a']}, "
        f"γ {econ['gamma']}, contact cost £{econ['contact_cost']:.0f}, value horizon "
        f"{econ['value_horizon_days']:.0f} days.",
        "",
        "| Policy | Contacted | Expected profit | Realized profit [95 % CI] | Share of oracle |",
        "|---|---|---|---|---|",
    ]
    for row in evaluation["policies"]:
        share = _share(row["share_of_oracle"])
        lines.append(
            f"| `{row['policy']}` | {row['n_contacted']:,} | {_gbp(row['expected_profit'])} | "
            f"{_gbp(row['realized_profit'])} [{_gbp(row['realized_profit_ci_low'])}, "
            f"{_gbp(row['realized_profit_ci_high'])}] | {share} |"
        )
    stability = pd.DataFrame(evaluation["stability"])
    deployed_rows = stability.loc[stability["model"] == name]
    lines += [
        "",
        f"The deployed policy realizes {_gbp(deployed['realized_profit'])} against "
        f"{_gbp(deployed['expected_profit'])} expected; expected and realized profit are always "
        "reported side by side because calibration across seasons is the central risk.",
        "",
        "## Calibration and profit across later cutoffs",
        "",
        "| Cutoff | Role | Churn rate | Mean p | ROC-AUC | Expected profit | Realized profit |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in deployed_rows.to_dict("records"):
        lines.append(
            f"| {row['cutoff']} | {row['role']} | {row['churn_rate']:.3f} | {row['mean_p']:.3f} | "
            f"{row['roc_auc']:.3f} | {_gbp(row['expected_profit'])} | "
            f"{_gbp(row['realized_profit'])} |"
        )
    top = importance.head(8)
    lines += [
        "",
        "## What drives the score",
        "",
        "Mean absolute SHAP value on the test cutoff, in log-odds of the uncalibrated score:",
        "",
        "| Feature | Mean abs. SHAP |",
        "|---|---|",
        *[f"| `{feature}` | {value:.3f} |" for feature, value in top.items()],
        "",
        "## Limitations and risks",
        "",
        "- **Seasonality:** the churn rate moves with the calendar and the holdout's label "
        "window covers the Q4 peak. Calibration is checked on every later cutoff above.",
        "- **Assumed economics:** the acceptance rate γ and the incentive and acquisition "
        "multipliers are assumptions, not measurements; the web app lets users change them.",
        "- **No treatment data:** profit assumes an accepted incentive retains the customer; the "
        "model predicts churn, not the effect of contacting.",
        "- **Small population:** a few thousand eligible customers per cutoff; CIs are wide.",
        "- **History-length features drift by construction** (tenure, totals grow as the data "
        "ages); their PSI against the training cutoffs is reported, not hidden.",
        "",
        "## Ethical considerations",
        "",
        "- The data identify customers only by a numeric ID; no personal attributes are used.",
        "- Country is used only as `is_uk`; decisions are commercial offers, not access to "
        "services.",
        "",
    ]
    return "\n".join(lines)
