// Generated by scripts/gen-contract.ts from contracts/schemas. Do not edit.
import type { ValidateFunction } from "ajv";

import type { Manifest } from "./types/manifest.gen.ts";
import type { CustomersFile } from "./types/customers.gen.ts";
import type { TimelinesFile } from "./types/timelines.gen.ts";
import type { EvaluationFile } from "./types/evaluation.gen.ts";
import type { ExperimentsFile } from "./types/experiments.gen.ts";
import type { FeatureSpec } from "./types/feature_spec.gen.ts";
import type { CalibratorFile } from "./types/calibrator.gen.ts";

export declare const validate_manifest: ValidateFunction<Manifest>;
export declare const validate_customers: ValidateFunction<CustomersFile>;
export declare const validate_timelines: ValidateFunction<TimelinesFile>;
export declare const validate_evaluation: ValidateFunction<EvaluationFile>;
export declare const validate_experiments: ValidateFunction<ExperimentsFile>;
export declare const validate_feature_spec: ValidateFunction<FeatureSpec>;
export declare const validate_calibrator: ValidateFunction<CalibratorFile>;
