/** The model card (spec §5.6), from the pinned release; the rest of the page never waits on it. */
import { lazy, Suspense } from "react";

export type CardResult = { ok: true; text: string } | { ok: false; reason: string };

const Rendered = lazy(() =>
  import("./ModelCardMarkdown.tsx").then((m) => ({ default: m.ModelCardMarkdown })),
);

export function ModelCard({ card }: { card: CardResult }) {
  return (
    <section
      id="model-card"
      aria-labelledby="model-card-title"
      className="scroll-mt-6 rounded-[10px] bg-panel p-5 shadow-[0_0_0_1px_var(--color-rule)]"
    >
      <h2 id="model-card-title" className="font-serif text-2xl">
        Model card
      </h2>
      <p className="mt-1 text-sm text-muted">
        Generated by the pipeline from the same run the site shows, and checked against the
        release's checksum.
      </p>
      {card.ok ? (
        <Suspense fallback={<p className="mt-3 text-sm text-muted">Loading the model card…</p>}>
          <Rendered text={card.text} />
        </Suspense>
      ) : (
        <p className="mt-3">The model card could not be read: {card.reason}.</p>
      )}
    </section>
  );
}
