/** The model card (spec §5.6), from the pinned release; a failure stays inside this section. */
import { CatchBoundary } from "@tanstack/react-router";
import { lazy, Suspense } from "react";

export type CardResult = { ok: true; text: string } | { ok: false; reason: string };

const Rendered = lazy(() =>
  import("./ModelCardMarkdown.tsx").then((m) => ({ default: m.ModelCardMarkdown })),
);

function Retry({ onRetry }: { onRetry: (() => void) | undefined }) {
  if (!onRetry) return null;
  return (
    <button type="button" className="mt-2 text-sm font-semibold text-accent" onClick={onRetry}>
      Try again
    </button>
  );
}

export function ModelCard({
  card,
  onRetry,
}: {
  card: CardResult;
  onRetry?: (() => void) | undefined;
}) {
  return (
    <section
      id="model-card"
      aria-labelledby="model-card-title"
      className="scroll-mt-6 rounded-[10px] bg-panel p-5 shadow-[0_0_0_1px_var(--color-rule)]"
    >
      <h2 id="model-card-title" className="font-serif text-2xl">
        Model card
      </h2>
      <p className="mt-1 text-sm text-muted">
        Generated by the pipeline from the same run the site shows, and checked against the
        release's checksum.
      </p>
      {card.ok ? (
        // The renderer is a lazy chunk: if it does not load, only this section says so.
        <CatchBoundary
          getResetKey={() => card.text}
          errorComponent={({ reset }) => (
            <div className="mt-3">
              <p>The model card could not be shown: its renderer did not load.</p>
              <Retry onRetry={reset} />
            </div>
          )}
        >
          <Suspense fallback={<p className="mt-3 text-sm text-muted">Loading the model card…</p>}>
            <Rendered text={card.text} />
          </Suspense>
        </CatchBoundary>
      ) : (
        <div className="mt-3">
          <p>The model card could not be read: {card.reason}.</p>
          <Retry onRetry={onRetry} />
        </div>
      )}
    </section>
  );
}
