// Generated by scripts/gen-contract.ts from contracts/schemas. Do not edit.
export interface CalibratorFile {
  calibrator: IsotonicSpec | PlattSpec;
  model: string;
}
/**
 * This interface was referenced by `CalibratorFile`'s JSON-Schema
 * via the `definition` "IsotonicSpec".
 */
export interface IsotonicSpec {
  method: "isotonic";
  /**
   * @minItems 1
   */
  x: [number, ...number[]];
  /**
   * @minItems 1
   */
  y: [number, ...number[]];
}
/**
 * This interface was referenced by `CalibratorFile`'s JSON-Schema
 * via the `definition` "PlattSpec".
 */
export interface PlattSpec {
  intercept: number;
  method: "platt";
  slope: number;
}
