// Generated by scripts/gen-contract.ts from contracts/schemas. Do not edit.
export interface CustomersFile {
  customers: Customer[];
  cutoff: string;
  deployed_model: string;
  horizon_days: number;
  models: string[];
}
/**
 * This interface was referenced by `CustomersFile`'s JSON-Schema
 * via the `definition` "Customer".
 */
export interface Customer {
  aov_gg: number;
  cadence_days: number;
  churn: 0 | 1;
  customer_id: number;
  features: {
    [k: string]: number;
  };
  p: {
    [k: string]: number;
  };
  shap_baseline: number;
  top_contributions: Contribution[];
}
/**
 * This interface was referenced by `CustomersFile`'s JSON-Schema
 * via the `definition` "Contribution".
 */
export interface Contribution {
  feature: string;
  shap: number;
  value: number;
}
