// Generated by scripts/gen-contract.ts from contracts/schemas. Do not edit.
export interface FeatureSpec {
  cadence_floor_days: number;
  context: {
    [k: string]: number;
  };
  features: FeatureEntry[];
  gamma_gamma: GammaGammaSpec;
  horizon_days: number;
  onnx_input: string;
  onnx_output: string;
  order: string[];
  spend_trend_eps: number;
}
/**
 * This interface was referenced by `FeatureSpec`'s JSON-Schema
 * via the `definition` "FeatureEntry".
 */
export interface FeatureEntry {
  description: string;
  dtype: "int" | "float";
  editable: boolean;
  group: "base" | "derived" | "context";
  max: number;
  min: number;
  name: string;
  unit: string;
}
/**
 * Gamma-Gamma parameters of the served cutoff: AOV^GG = p(v + x m) / (p x + q - 1).
 *
 * This interface was referenced by `FeatureSpec`'s JSON-Schema
 * via the `definition` "GammaGammaSpec".
 */
export interface GammaGammaSpec {
  p: number;
  q: number;
  v: number;
}
