// Generated by scripts/gen-contract.ts from contracts/schemas. Do not edit.
export interface ModelGolden {
  cases: ModelCase[];
  model: string;
  order: string[];
  tolerance: number;
}
/**
 * This interface was referenced by `ModelGolden`'s JSON-Schema
 * via the `definition` "ModelCase".
 */
export interface ModelCase {
  features: number[];
  p: number;
  score: number;
}
