// Generated by scripts/gen-contract.ts from contracts/schemas. Do not edit.
export interface EconomicsGolden {
  budget_cases: BudgetCase[];
  cases: EconomicsCase[];
  tolerance: number;
}
/**
 * This interface was referenced by `EconomicsGolden`'s JSON-Schema
 * via the `definition` "BudgetCase".
 */
export interface BudgetCase {
  budget: number | null;
  expected_cost: number[];
  expected_profit: number[];
  max_contacts: number | null;
  selected: boolean[];
}
/**
 * This interface was referenced by `EconomicsGolden`'s JSON-Schema
 * via the `definition` "EconomicsCase".
 */
export interface EconomicsCase {
  aov_gg: number;
  benefit: number;
  break_even_p: number;
  cac: number;
  cadence_days: number;
  churn: 0 | 1;
  contact: boolean;
  crc: number;
  expected_cost: number;
  expected_profit: number;
  p: number;
  params: EconomicParams;
  realized_profit: number;
  value: number;
}
/**
 * User-configurable business assumptions. Defaults live in configs/default.yaml.
 *
 * This interface was referenced by `EconomicsGolden`'s JSON-Schema
 * via the `definition` "EconomicParams".
 */
export interface EconomicParams {
  contact_cost: number;
  gamma: number;
  lambda_a: number;
  lambda_c: number;
  margin: number;
  value_horizon_days: number;
}
