// Generated by scripts/gen-contract.ts from contracts/schemas. Do not edit.
export interface GammaGammaGolden {
  cases: GammaGammaCase[];
  tolerance: number;
}
/**
 * This interface was referenced by `GammaGammaGolden`'s JSON-Schema
 * via the `definition` "GammaGammaCase".
 */
export interface GammaGammaCase {
  aov_gg: number;
  avg_order_value: number;
  n_purchase_days: number;
  params: GammaGammaSpec;
}
/**
 * Gamma-Gamma parameters of the served cutoff: AOV^GG = p(v + x m) / (p x + q - 1).
 *
 * This interface was referenced by `GammaGammaGolden`'s JSON-Schema
 * via the `definition` "GammaGammaSpec".
 */
export interface GammaGammaSpec {
  p: number;
  q: number;
  v: number;
}
