// Generated by scripts/gen-contract.ts from contracts/schemas. Do not edit.
export interface DerivedGolden {
  cadence_floor_days: number;
  cases: DerivedCase[];
  horizon_days: number;
  spend_trend_eps: number;
  tolerance: number;
}
/**
 * This interface was referenced by `DerivedGolden`'s JSON-Schema
 * via the `definition` "DerivedCase".
 */
export interface DerivedCase {
  base: {
    [k: string]: number;
  };
  derived: {
    [k: string]: number;
  };
}
