// Generated by scripts/gen-contract.ts from contracts/schemas. Do not edit.
export interface Manifest {
  config_sha256: string;
  contract_version: string;
  created_at: string;
  data_sha256: string;
  deployed_model: string;
  files: {
    [k: string]: string;
  };
  git_sha: string;
  models: ModelInfo[];
  pipeline?: PipelineInfo | null;
  test_cutoff: string;
}
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "ModelInfo".
 */
export interface ModelInfo {
  deployable: boolean;
  family: "rule" | "probabilistic" | "linear" | "gbdt";
  label: string;
  name: string;
}
/**
 * How the served run was built (contract 1.2.0): the Model and Method pages quote it.
 *
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "PipelineInfo".
 */
export interface PipelineInfo {
  eligibility_f: number;
  horizon_days: number;
  n_folds: number;
  n_trials: number;
  seed: number;
}
