// Generated by scripts/gen-contract.ts from contracts/schemas. Do not edit.
export interface TimelinesFile {
  cutoff: string;
  horizon_days: number;
  timelines: Timeline[];
}
/**
 * This interface was referenced by `TimelinesFile`'s JSON-Schema
 * via the `definition` "Timeline".
 */
export interface Timeline {
  customer_id: number;
  days: number[];
  revenue: number[];
}
